# Generated by Django 3.1.7 on 2021-03-08 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210308_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.profile'),
        ),
    ]
