# Generated by Django 3.1.7 on 2021-03-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210308_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='uname',
            new_name='uid',
        ),
    ]
